### ISSUE TITLE
Fix Build Issue w/ CircleCI & GH Credentials

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/redhat-ipaas.github.io#20]
Auto-deploy build fails when pushing directly to the `source` branch, but deploying locally with `bundle exec middleman deploy` works fine. Seems to be an issue with GH credentials (not specifying any in `circle.yml` but didn't need to before). Also the following settings in `circle.yml` were resulting in a different error as well:

```
# circle.yml

machine:
  timezone:
    America/New_York
  ruby:
    version: 2.4.0

dependencies:
  pre:
    - gem install bundler
    - gem install middleman-cli

checkout:
  post:
    - bundle install

compile:
  override:
    - bundle exec middleman build

deployment:
  build:
    branch: source
    commands:
      - git config user.email $GIT_USER_EMAIL
      - git config user.name $GIT_USER_NAME
      - bundle exec middleman deploy --verbose

# Skip Tests
test:
  override:
    - "true"
```

After removing `git` commands, I got the following error, logically: https://gist.github.com/kahboom/11b27368bd907c52d2035c506afcb2a1

Should be easy, but need to resolve this. jimmibot seems to have proper access so not sure why it wouldn't pick up those ENV vars set my Circle.
